AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main CloudFormation template for ApiBTG - Orchestrates all resources'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]
    Description: Environment name

  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    AllowedValues: [db.t3.micro, db.t3.small, db.t3.medium, db.r5.large, db.r5.xlarge]
    Description: RDS instance class

  DBName:
    Type: String
    Default: BTG
    Description: Database name

  DBUsername:
    Type: String
    Default: admin
    Description: Database master username

  DBPassword:
    Type: String
    NoEcho: true
    Description: Database master password
    MinLength: 8

  JwtKey:
    Type: String
    NoEcho: true
    Description: JWT secret key
    MinLength: 16

  MailtrapUsername:
    Type: String
    NoEcho: true
    Description: Mailtrap username

  MailtrapPassword:
    Type: String
    NoEcho: true
    Description: Mailtrap password

  TwilioAccountSid:
    Type: String
    NoEcho: true
    Description: Twilio Account SID

  TwilioAuthToken:
    Type: String
    NoEcho: true
    Description: Twilio Auth Token

  ImageUri:
    Type: String
    Default: your-account.dkr.ecr.region.amazonaws.com/apibtg:latest
    Description: ECR image URI

  ContainerPort:
    Type: Number
    Default: 80
    Description: Container port

  DesiredCount:
    Type: Number
    Default: 2
    MinValue: 1
    MaxValue: 10
    Description: Desired number of tasks

  Cpu:
    Type: String
    Default: 256
    AllowedValues: [256, 512, 1024, 2048, 4096]
    Description: CPU units for the task

  Memory:
    Type: String
    Default: 512
    AllowedValues: [512, 1024, 2048, 4096, 8192, 16384]
    Description: Memory (MiB) for the task

Resources:
  # VPC Stack
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yaml
      Parameters:
        Environment: !Ref Environment

  # Secrets Stack
  SecretsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: secrets.yaml
      Parameters:
        Environment: !Ref Environment
        JwtKey: !Ref JwtKey
        MailtrapUsername: !Ref MailtrapUsername
        MailtrapPassword: !Ref MailtrapPassword
        TwilioAccountSid: !Ref TwilioAccountSid
        TwilioAuthToken: !Ref TwilioAuthToken

  # RDS Stack
  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: rds.yaml
      Parameters:
        Environment: !Ref Environment
        DBInstanceClass: !Ref DBInstanceClass
        DBName: !Ref DBName
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PrivateSubnet1Id: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VPCStack.Outputs.PrivateSubnet2Id

  # ECS Stack
  ECSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - VPCStack
      - RDSStack
      - SecretsStack
    Properties:
      TemplateURL: ecs.yaml
      Parameters:
        Environment: !Ref Environment
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnet1Id: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt VPCStack.Outputs.PublicSubnet2Id
        PrivateSubnet1Id: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VPCStack.Outputs.PrivateSubnet2Id
        DBSecretArn: !GetAtt RDSStack.Outputs.DBSecretArn
        ImageUri: !Ref ImageUri
        ContainerPort: !Ref ContainerPort
        DesiredCount: !Ref DesiredCount
        Cpu: !Ref Cpu
        Memory: !Ref Memory

Outputs:
  # VPC Outputs
  VPCId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VPCId
    Export:
      Name: !Sub '${Environment}-ApiBTG-Main-VPC-ID'

  # Database Outputs
  DBEndpoint:
    Description: Database endpoint
    Value: !GetAtt RDSStack.Outputs.DBEndpoint
    Export:
      Name: !Sub '${Environment}-ApiBTG-Main-DB-Endpoint'

  # Application Outputs
  ALBDNSName:
    Description: Application Load Balancer DNS Name
    Value: !GetAtt ECSStack.Outputs.ALBDNSName
    Export:
      Name: !Sub '${Environment}-ApiBTG-Main-ALB-DNS'

  ECSClusterName:
    Description: ECS Cluster Name
    Value: !GetAtt ECSStack.Outputs.ECSClusterName
    Export:
      Name: !Sub '${Environment}-ApiBTG-Main-ECS-Cluster-Name'

  ECSServiceName:
    Description: ECS Service Name
    Value: !GetAtt ECSStack.Outputs.ECSServiceName
    Export:
      Name: !Sub '${Environment}-ApiBTG-Main-ECS-Service-Name'

  # API Endpoint
  APIEndpoint:
    Description: API Endpoint URL
    Value: !Sub 'http://${ECSStack.Outputs.ALBDNSName}'
    Export:
      Name: !Sub '${Environment}-ApiBTG-Main-API-Endpoint' 