AWSTemplateFormatVersion: '2010-09-09'
Description: 'Secrets Manager for ApiBTG'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]
    Description: Environment name

  JwtKey:
    Type: String
    NoEcho: true
    Description: JWT secret key
    MinLength: 16

  MailtrapUsername:
    Type: String
    NoEcho: true
    Description: Mailtrap username

  MailtrapPassword:
    Type: String
    NoEcho: true
    Description: Mailtrap password

  TwilioAccountSid:
    Type: String
    NoEcho: true
    Description: Twilio Account SID

  TwilioAuthToken:
    Type: String
    NoEcho: true
    Description: Twilio Auth Token

Resources:
  # JWT Secret
  JwtSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${Environment}/apibtg/jwt'
      Description: JWT settings for ApiBTG
      SecretString: !Sub |
        {
          "key": "${JwtKey}",
          "Issuer": "https://api.apibtg.com",
          "Audience": "https://api.apibtg.com"
        }
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-ApiBTG-JWT-Secret'

  # Email Settings Secret
  EmailSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${Environment}/apibtg/email'
      Description: Email settings for ApiBTG
      SecretString: !Sub |
        {
          "SmtpServer": "sandbox.smtp.mailtrap.io",
          "Port": 2525,
          "SenderName": "Api BTG",
          "SenderEmail": "test@btg.com",
          "Username": "${MailtrapUsername}",
          "Password": "${MailtrapPassword}"
        }
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-ApiBTG-Email-Secret'

  # Twilio Secret
  TwilioSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${Environment}/apibtg/twilio'
      Description: Twilio settings for ApiBTG
      SecretString: !Sub |
        {
          "AccountSid": "${TwilioAccountSid}",
          "AuthToken": "${TwilioAuthToken}",
          "FromNumber": "+12513365758"
        }
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-ApiBTG-Twilio-Secret'

Outputs:
  JwtSecretArn:
    Description: JWT Secret ARN
    Value: !Ref JwtSecret
    Export:
      Name: !Sub '${Environment}-ApiBTG-JWT-Secret-ARN'

  EmailSecretArn:
    Description: Email Secret ARN
    Value: !Ref EmailSecret
    Export:
      Name: !Sub '${Environment}-ApiBTG-Email-Secret-ARN'

  TwilioSecretArn:
    Description: Twilio Secret ARN
    Value: !Ref TwilioSecret
    Export:
      Name: !Sub '${Environment}-ApiBTG-Twilio-Secret-ARN' 